### ISSUE TITLE
How to setup bolt protocol listener for AWS Classic load balancer

### ISSUE THREAD

**Issue by Balatriveni** [boltprotocol/boltprotocol#10]
We have a neo4j EC2 instance, we want to add that to Auto scaling group with AWS ELB load balancer.
When  I access the neo4j browser with Load balancer DNS name it works, but bolt connect does nt work.
How to setup AWS Load balancer for neo4j EC2 instance

**Comment by cleishm** [comment]
Hey @Balatriveni,

This repository hosts the protocol specification for Bolt. If you want assistance with neo4j, I suggest heading over to their website at https://support.neo4j.com/hc/en-us, or github at https://github.com/neo4j/neo4j. Good luck with your issue!

Cheers,
Chris
