### ISSUE TITLE
Is there a `mod_proxy` plugin for bolt protocol?

### ISSUE THREAD

**Issue by pikrzysztof** [boltprotocol/boltprotocol#4]
I am running neo4j behind Apache proxy. I am using [`mod_proxy`](https://httpd.apache.org/docs/current/mod/mod%5Fproxy.html) to route the traffic, but since bolt is not a standard protocol I couldn't find a `mod_proxy` plug-in for `bolt`.

Is there an Apache `mod_proxy` plugin for `bolt` protocol?

**Comment by cleishm** [comment]
Hi @pikrzysztof,

Not that I'm aware of. Would be a great thing for someone to work on!

Cheers,
Chris
